### ISSUE TITLE
SAVE attribute not working

### ISSUE THREAD

**Issue by pjh40** [lfortran/lfortran#5308] opened 2024-11-09 14:36 UTC
Given the code
```f90
subroutine foo
  integer, save :: calls = 0
  calls = calls + 1
  print *, 'FOO: ', calls
end subroutine foo


program test
  integer i
  do i=1,3
     call foo
  end do
end program test
```
I would expect output similar to GCC:
```sh
 FOO:            1
 FOO:            2
 FOO:            3
```
but I'm getting:
```sh
FOO:     1
FOO:     1
FOO:     1
```
The `AttrSave` attribute does show up in the AST:
```
(TranslationUnit
    [(Subroutine
        foo
        []
        []
        ()
        (TriviaNode
            []
            [(EndOfLine)
            (EndOfLine)
            (EndOfLine)]
        )
        []
        []
        []
        [(Declaration
            (AttrType
                TypeInteger
                []
                ()
                ()
                None
            )
            [(SimpleAttribute
                AttrSave
            )]
            [(calls
            []
            []
            ()
            0
            Equal
            ())]
            ()
        )]
        [(Assignment
            0
            calls
            (+ calls 1)
            ()
        )
 ```
 and appears to be in the ASR as well, but I'm still learning how to read those:
 ```
 (TranslationUnit
    (SymbolTable
        1
        {
            foo:
                (Function
                    (SymbolTable
                        2
                        {
                            calls:
                                (Variable
                                    2
                                    calls
                                    []
                                    Local
                                    (IntegerConstant 0 (Integer 4) Decimal)
                                    (IntegerConstant 0 (Integer 4) Decimal)
                                    Save
                                    (Integer 4)
                                    ()
                                    Source
                                    Public
                                    Required
                                    .false.
                                )
                        })
                    foo
                    (FunctionType
                        []
                        ()
                        Source
                        Implementation
                        ()
                        .false.
                        .false.
                        .false.
                        .false.
                        .false.
                        []
                        .false.
                    )
                    []
                    []
                    [(Assignment
                        (Var 2 calls)
                        (IntegerBinOp
                            (Var 2 calls)
                            Add
                            (IntegerConstant 1 (Integer 4) Decimal)
                            (Integer 4)
                            ()
                        )
                        ()
                    )
  ```
  This is on `main` SHA 1db1cae4e5eae49b1df25dd.

**Comment by certik** [comment] 2024-11-09 15:39
Thanks! I can reproduce it. It's weird, we definitely support `save`, but apparently not in this case. The initial ASR is correct (https://github.com/lfortran/lfortran/issues/5309#issuecomment-2466260653), so the bug happens later.

**Comment by pjh40** [comment] 2024-11-09 16:18
Thanks for walking through your debugging process in detail... it gives me some more tools to help me do better reporting and maybe even bug fixing!

**Comment by certik** [comment] 2024-11-09 16:20
@pjh40 thanks for reporting bugs and your contributions!

Here is a good test to add to our integration suite once we fix this:
```fortran
subroutine foo(reference)
  integer, intent(in) :: reference
  integer, save :: calls = 0
  calls = calls + 1
  print *, 'FOO: ', calls, reference
  if (calls /= reference) error stop
end subroutine foo

program test_save
  integer i
  do i=1,3
     call foo(i)
  end do
end program test_save
```

**Comment by certik** [comment] 2024-11-09 17:02
Looking at our current tests for `save` and the behavior of LFortran it looks like we support `save` but only if you assign to it later. The initializer such as `integer, save :: x = 5` assigns the 5 inside the function, and initializes to 0 globally. To fix this, for simple variables like integers / floats we should initialize the global variable appropriately, and for complex types we need to do the initialization in the main program.

**Comment by Pranavchiku** [comment] 2024-11-09 17:09
To debug further, we are processing a variable inside `asr_to_llvm` , so we got to `process_Variable` and in that if we look at the `m_symbolic_value` or `m_value` which is shown in the ASR below 

```ASR
(Variable
    2
    calls
    []
    Local
    (IntegerConstant 0 (Integer 4) Decimal) ---------- m_symbolic_value
    (IntegerConstant 0 (Integer 4) Decimal) ---------- m_value
    Save
    (Integer 4)
    ()
    Source
    Public
    Required
    .false.
)
```

and apply the following diff:

```diff
diff --git a/src/libasr/codegen/asr_to_llvm.cpp b/src/libasr/codegen/asr_to_llvm.cpp
index 8bff00634..66172d5eb 100644
--- a/src/libasr/codegen/asr_to_llvm.cpp
+++ b/src/libasr/codegen/asr_to_llvm.cpp
@@ -3810,7 +3810,14 @@ public:
                         strings_to_be_deallocated.push_back(al, llvm_utils->CreateLoad2(v->m_type, target_var));
                     }
                 } else {
-                    builder->CreateStore(init_value, target_var);
+                    if (v->m_storage == ASR::storage_typeType::Save) {
+                        llvm::GlobalVariable *gptr = module->getNamedGlobal(
+                            std::string(x.m_name) + "." + v->m_name);
+                        llvm::Constant *init_value = llvm::dyn_cast<llvm::Constant>(tmp);
+                        gptr->setInitializer(init_value);
+                    } else {
+                        builder->CreateStore(init_value, target_var);
+                    }
                 }
             } else {
                 if (is_a<ASR::String_t>(*v->m_type) && !is_array_type && !is_list) {
```

The only trouble is to handle cases like

```fortran
program main
    complex, save :: ci = (1.0, 2.0)
end program
```

**Comment by certik** [comment] 2024-11-09 17:27
First part of the fix is to set the global value correctly:
```diff
--- a/src/libasr/codegen/asr_to_llvm.cpp
+++ b/src/libasr/codegen/asr_to_llvm.cpp
@@ -3672,7 +3672,13 @@ public:
                     ptr = module->getOrInsertGlobal(global_name, type);
                     llvm::GlobalVariable *gptr = module->getNamedGlobal(global_name);
                     gptr->setLinkage(llvm::GlobalValue::InternalLinkage);
-                    llvm::Constant *init_value = llvm::Constant::getNullValue(type);
+                    llvm::Constant *init_value;
+                    if (v->m_value) {
+                        this->visit_expr(*v->m_value);
+                        init_value = llvm::dyn_cast<llvm::Constant>(tmp);
+                    } else {
+                        init_value = llvm::Constant::getNullValue(type);
+                    }
                     gptr->setInitializer(init_value);
 #if LLVM_VERSION_MAJOR > 16
                     ptr_type[ptr] = type;
```
And the second part of the fix is to not set it inside the function.

The third part is to only do this for integer/real/logical, but for more complex types initialize in the main program. This can be done in subsequent PRs.

**Comment by certik** [comment] 2024-11-09 22:57
Thanks @Pranavchiku, that was helpful to get it done.

This particular issue is fixed by the pair of PRs https://github.com/lfortran/lfortran/pull/5316 and https://github.com/lfortran/lfortran/pull/5317.

It still doesn't work for more complex types, so I created a dedicated issue for that at https://github.com/lfortran/lfortran/issues/5319.

**Closed** 2024-11-09 23:23 UTC
Labels: bug
