### ISSUE TITLE
"Double complex" is not parsed

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#443] opened 2022-08-15 09:15 UTC
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/585

Scipy's scipy/_build_utils/src
````
+ lfortran --show-ast --fixed-form wrap_dummy_g77_abi.f
input:15:8 syntax error: token type 'complex' is unexpected here
DOUBLE COMPLEX FUNCTION WZDOTC( N, CX, INCX, CY, INCY )
       ^~~~~~~
Parsing error: syntax error
```

**Comment by konradha** [comment] 2022-09-14 13:09
duplicate of #653

**Closed by konradha** 2022-09-14 13:09 UTC
Labels: SciPy
