### ISSUE TITLE
bug: `init_value` is not available for some global variable types

### ISSUE THREAD

**Issue by kmr-srbh** [lfortran/lfortran#4120] opened 2024-05-30 13:21 UTC
This bug was caught when working on #4115 

```fortran
module test_init_value_module
   integer, dimension(4) :: arr = [1, 2, 3, 4]
end module test_init_value_module

program test_init_value_program
   use test_init_value_module
   print *, arr 
end program test_init_value_program
```
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
0 0 0 0 
```

For `Array`, the `init_value` is not handled and thus we do not initialize it with the value. However, even after handling the `init_value`, we find that the value is actually not available. The same is the case for all the data-structure types like `List`, `Dict`, `Set`, etc.

The chief cause of the issue is the use of `llvm::dyn_cast<T>` to convert  `init_value`, which is of type `llvm::Value*`, to `llvm::Constant`. This being an incorrect cast (`llvm::Value` is the super class of `llvm::Constant`) returns a `nullptr` for some data-types.

**Comment by gxyd** [comment] 2024-05-30 14:12
Possibly duplicate of https://github.com/lfortran/lfortran/issues/3897 ? I think the analysis was different from what you mentioned above for the cause of issue?

**Comment by kmr-srbh** [comment] 2024-05-30 14:25
When analyzing the issue, I found that due to the dynamic cast, the value of `init_value` was being set to `nullptr`, hence we never reach the piece of code which does this initialization. 

Here is what the LLVM Programmer's Manual has to say about `llvm::dyn_cast`:
> The dyn_cast<> operator is a “checking cast” operation. It checks to see if the operand is of the specified type, and if so, returns a pointer to it (this operator does not work with references). If the operand is not of the correct type, a null pointer is returned.

**Comment by gxyd** [comment] 2024-05-31 08:32
I meant that I'm not so sure if the reason of bug is what's explained via LLVM dynamic cast (I don't know much about that explanation), but seemed like the reason for non-initialization of an array imported from module is what's expected from an ASR pass (as mentioned in the linked issue)

**Closed** 2024-06-01 17:50 UTC
Labels: bug, duplicate
