### ISSUE TITLE
bug: add basic support for `tuple` type

### ISSUE THREAD

**Issue by kmr-srbh** [lfortran/lfortran#4173] opened 2024-06-07 06:28 UTC
### Minimum Reproducible Example

```fortran

MODULE setup_module
   IMPLICIT NONE

   INTEGER :: nmat=2
   INTEGER :: ng=1

   REAL, ALLOCATABLE, DIMENSION(:,:) :: sigt

CONTAINS

   SUBROUTINE setup_echo

      INTEGER :: i, j
      ALLOCATE (sigt(nmat, ng))

      DO j = 1, 2
         print *, ( i, sigt(j,i), i = 1, ng )
      END DO

   END SUBROUTINE setup_echo

END MODULE setup_module

PROGRAM example
   USE setup_module
   CALL setup_echo
END PROGRAM example
```

### Output
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
duplicate type: tuple
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran", in _start()
  File "./csu/../csu/libc-start.c", line 360, in __libc_start_main_impl()
  File "./csu/../sysdeps/x86/libc-start.c", line 58, in __libc_start_call_main()
  File "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran.cpp", line 2473, in main()
    return main_app(argc, argv);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran.cpp", line 2434, in main_app(int, char**)
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/home/saurabh-kumar/Projects/System/lfortran/src/bin/lfortran.cpp", line 948, in compile_to_object_file()
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/lfortran/fortran_evaluator.cpp", line 359, in LCompilers::FortranEvaluator::get_llvm3(LCompilers::ASR::TranslationUnit_t&, LCompilers::PassManager&, LCompilers::diag::Diagnostics&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    compiler_options, run_fn, infile);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9898, in LCompilers::asr_to_llvm(LCompilers::ASR::TranslationUnit_t&, LCompilers::diag::Diagnostics&, llvm::LLVMContext&, Allocator&, LCompilers::PassManager&, LCompilers::CompilerOptions&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/pass/pass_manager.h", line 311, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/pass/pass_manager.h", line 167, in LCompilers::PassManager::apply_passes(Allocator&, LCompilers::ASR::TranslationUnit_t*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, LCompilers::PassOptions&, LCompilers::diag::Diagnostics&)
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/pass/implied_do_loops.cpp", line 685, in LCompilers::pass_replace_implied_do_loops(Allocator&, LCompilers::ASR::TranslationUnit_t&, LCompilers::PassOptions const&)
    v.visit_TranslationUnit(unit);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 46823, in LCompilers::ASR::CallReplacerOnExpressionsVisitor<LCompilers::ArrayConstantVisitor>::visit_TranslationUnit(LCompilers::ASR::TranslationUnit_t const&)
    this->visit_symbol(*a.second);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 5143, in LCompilers::ASR::BaseVisitor<LCompilers::ArrayConstantVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 4856, in visit_symbol_t<LCompilers::ArrayConstantVisitor>()
    case symbolType::Module: { v.visit_Module((const Module_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 46841, in LCompilers::ASR::CallReplacerOnExpressionsVisitor<LCompilers::ArrayConstantVisitor>::visit_Module(LCompilers::ASR::Module_t const&)
    this->visit_symbol(*a.second);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 5143, in LCompilers::ASR::BaseVisitor<LCompilers::ArrayConstantVisitor>::visit_symbol(LCompilers::ASR::symbol_t const&)
    void visit_symbol(const symbol_t &b) { visit_symbol_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 4857, in visit_symbol_t<LCompilers::ArrayConstantVisitor>()
    case symbolType::Function: { v.visit_Function((const Function_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 46861, in LCompilers::ASR::CallReplacerOnExpressionsVisitor<LCompilers::ArrayConstantVisitor>::visit_Function(LCompilers::ASR::Function_t const&)
    self().transform_stmts(xx.m_body, xx.n_body);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/pass/implied_do_loops.cpp", line 457, in LCompilers::ArrayConstantVisitor::transform_stmts(LCompilers::ASR::stmt_t**&, unsigned long&)
    visit_stmt(*m_body[i]);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 5160, in LCompilers::ASR::BaseVisitor<LCompilers::ArrayConstantVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 4887, in visit_stmt_t<LCompilers::ArrayConstantVisitor>()
    case stmtType::DoLoop: { v.visit_DoLoop((const DoLoop_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 47124, in LCompilers::ASR::CallReplacerOnExpressionsVisitor<LCompilers::ArrayConstantVisitor>::visit_DoLoop(LCompilers::ASR::DoLoop_t const&)
    self().transform_stmts(xx.m_body, xx.n_body);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/pass/implied_do_loops.cpp", line 457, in LCompilers::ArrayConstantVisitor::transform_stmts(LCompilers::ASR::stmt_t**&, unsigned long&)
    visit_stmt(*m_body[i]);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 5160, in LCompilers::ASR::BaseVisitor<LCompilers::ArrayConstantVisitor>::visit_stmt(LCompilers::ASR::stmt_t const&)
    void visit_stmt(const stmt_t &b) { visit_stmt_t(b, self()); }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 4895, in visit_stmt_t<LCompilers::ArrayConstantVisitor>()
    case stmtType::Print: { v.visit_Print((const Print_t &)x); return; }
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/pass/implied_do_loops.cpp", line 550, in LCompilers::ArrayConstantVisitor::visit_Print(LCompilers::ASR::Print_t const&)
    this->call_replacer();
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/pass/implied_do_loops.cpp", line 438, in LCompilers::ArrayConstantVisitor::call_replacer()
    replacer.replace_expr(*current_expr);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr.h", line 46016, in LCompilers::ASR::BaseExprReplacer<LCompilers::ReplaceArrayConstant>::replace_expr(LCompilers::ASR::expr_t*)
    self().replace_ArrayConstructor(down_cast<ASR::ArrayConstructor_t>(x));
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/pass/implied_do_loops.cpp", line 240, in LCompilers::ReplaceArrayConstant::replace_ArrayConstructor(LCompilers::ASR::ArrayConstructor_t*)
    result_type_ = ASRUtils::TYPE(ASR::make_Allocatable_t(al, x->m_type->base.loc,
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr_utils.h", line 2689, in duplicate_type_with_empty_dims()
    return duplicate_type(al, t, &empty_dims, physical_type, override_physical_type);
  File "/home/saurabh-kumar/Projects/System/lfortran/src/libasr/../libasr/asr_utils.h", line 2532, in duplicate_type()
    ASR::ttype_t* duplicated_element_type = duplicate_type(al, tnew->m_type);
LCompilersException: Not implemented 8
```

The bug was found when trying to compile the file `snap_main.f90`. The file imports from `setup.f90` where we have a function which does the above processing.

The chief cause of the issue here is the way we handle types in `ImpliedDoLoop_t`. When the types are not same, we try to create a `tuple` for holding dissimilar types.
```c++
if (!unique_type) {
    type = ASRUtils::TYPE(ASR::make_Tuple_t(al, x.base.base.loc, type_tuple.p, type_tuple.size()));
}
```
where `unique_type` is handled as
```c++
if (!unique_type || !ASRUtils::types_equal(type_, type)) {
    unique_type = false;
}
```
<br>

GFortran does not throw an error here and instead handles both the types together. 
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ gfortran ./examples/example.f90 && ./a.out
           1   0.00000000    
           1   0.00000000 
```
Here is the relevant line from the output of `-fdump-tree-all`.
```c++
_gfortran_transfer_real_write (&dt_parm.3, &(*(real(kind=4)[0:] * restrict) sigt.data)[(sigt.offset + (integer(kind=8)) i * sigt.dim[1].stride) + (integer(kind=8)) j], 4);
```

**Comment by certik** [comment] 2024-06-07 19:02
Good catch and analysis. Yes, we need to handle `( i, sigt(j,i), i = 1, ng )` correctly. I think it creates alternating `i, sigt(j,i)` as `i` increases. I am not sure using the tuple is the right approach here. I think we just need to create the correct array and alternate the two elements.

**Comment by kmr-srbh** [comment] 2024-06-08 08:56
Do we support arrays of different types? If not, then we will have to do implicit casting here which will change the type of elements.

**Comment by Pranavchiku** [comment] 2024-06-12 05:49
You cannot store it in any `Array`, check the following example:

```fortran
MODULE setup_module
   IMPLICIT NONE

   INTEGER :: nmat=2
   INTEGER :: ng=1

   REAL, ALLOCATABLE, DIMENSION(:,:) :: sigt
   double precision, ALLOCATABLE, DIMENSION(:,:) :: sigt2
CONTAINS

   SUBROUTINE setup_echo

      INTEGER :: i, j
      INTEGER :: x(6)
      ALLOCATE (sigt(nmat, ng))
      ALLOCATE (sigt2(nmat, ng))

      x = [( i, sigt(j,i), sigt2(j,i), i = 1, ng )]
      print *, x

      DO j = 1, 2
         print *, ( i, sigt(j,i), sigt2(j,i), i = 1, ng )
      END DO

   END SUBROUTINE setup_echo

END MODULE setup_module

PROGRAM example
   USE setup_module
   CALL setup_echo
END PROGRAM example
```

```console
% gfortran a.f90 && ./a.out
a.f90:19:15:

   19 |       x = [( i, sigt(j,i), sigt2(j,i), i = 1, ng )]
      |               1
Error: Element in INTEGER(4) array constructor at (1) is REAL(4)
a.f90:31:8:

   31 |    USE setup_module
      |        1
Fatal Error: Cannot open module file 'setup_module.mod' for reading at (1): No such file or directory
compilation terminated.
```

This does not even work with GFortran, so this type of `Tuple` type will only work for `print *`, `write`, etc. This will be straight forward to fix, you have to go to `visit_Print` in `implied_do_loops.cpp` and handle `tuple` there.

**Comment by Pranavchiku** [comment] 2024-06-17 18:59
MODULE setup_module
   IMPLICIT NONE

   INTEGER :: nmat=2
   INTEGER :: ng=1

   REAL, ALLOCATABLE, DIMENSION(:,:) :: sigt

CONTAINS

   SUBROUTINE setup_echo

      INTEGER :: i, j
      ALLOCATE (sigt(nmat, ng))

      DO j = 1, 2
          DO i = 1, ng
             print *, i, sight(j, i)
          END DO
      END DO

   END SUBROUTINE setup_echo

END MODULE setup_module

PROGRAM example
   USE setup_module
   CALL setup_echo
END PROGRAM example

**Comment by certik** [comment] 2024-06-18 15:20
If the types are the same, such as in the following example, then it seems to be working:
```fortran
MODULE setup_module
   IMPLICIT NONE

   INTEGER :: nmat=2
   INTEGER :: ng=2

   integer, ALLOCATABLE, DIMENSION(:,:) :: sigt
   integer, ALLOCATABLE, DIMENSION(:,:) :: sigt2
CONTAINS

   SUBROUTINE setup_echo

      INTEGER :: i, j
      INTEGER :: x(6)
      ALLOCATE (sigt(nmat, ng))
      ALLOCATE (sigt2(nmat, ng))

      sigt = 5
      sigt2 = 6
      j = 1

      x = [( i, sigt(j,i), sigt2(j,i), i = 1, ng )]
      print *, x

      DO j = 1, 2
         print *, ( i, sigt(j,i), sigt2(j,i), i = 1, ng )
      END DO

   END SUBROUTINE setup_echo

END MODULE setup_module

PROGRAM example
   USE setup_module
   CALL setup_echo
END PROGRAM example
```

So the issue is if the types are not the same. In that case we can't assign it to an array. The only use case is printing.

I am not sure we should be using tuples, because tuples are usually printed like this:
```console
>>> (1, 2, 3)
(1, 2, 3)
```
With parentheses. We could create some special formatting string for that, but it seems complicated.

The `ng` above is a runtime variable, so we need to handle any such runtime loops. I think we need to transform it into:
```
      DO j = 1, 2
          DO i = 1, ng
             write(*,*,advance=no)  i, sigt(j,i), sigt2(j,i)
          END DO
      END DO
```
probably in an ASR->ASR pass, then it should work.

**Comment by certik** [comment] 2024-06-18 15:36
To fix this, we could possibly even use a tuple to store the `i, sigt(j,i), sigt2(j,i)` part of the implied do loop `( i, sigt(j,i), sigt2(j,i), i = 1, ng )` if that makes things easier to represent in ASR. It might be similar to Python's:
```console
>>> print([(i, sigt[i], sigt2[i]) for i in range(ng)])
[(0, 1, 5), (1, 2, 6), (2, 3, 7)]
```
However there it prints three tuples, with parentheses. So we need this feature, but how do we distinguish in ASR if the input came from Fortran or Python, in order to decide if to print the parentheses?

So either we don't use tuples, or we somehow represent that.

**Comment by Pranavchiku** [comment] 2024-08-23 08:12
MRE:

```fortran
PROGRAM example
INTEGER :: i
REAL, DIMENSION(5) :: A
A = 12.9
print *, ( i, A(i), i = 1, 2)
END PROGRAM example
```
```console
% lfortran a.f90 
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2479
    LCompilers::print_stack_on_segfault();
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2443
    err = compile_to_object_file(arg_file, tmp_o, false,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 954
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 363
    compiler_options, run_fn, infile);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 10170
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 315
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 169
    _passes_db[passes[i]](al, *asr, pass_options);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/implied_do_loops.cpp", line 685
    v.visit_TranslationUnit(unit);
  File "../libasr/asr.h", line 46903
  File "../libasr/asr.h", line 5137
  File "../libasr/asr.h", line 4850
  File "../libasr/asr.h", line 46915
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/implied_do_loops.cpp", line 457
    visit_stmt(*m_body[i]);
  File "../libasr/asr.h", line 5154
  File "../libasr/asr.h", line 4889
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/implied_do_loops.cpp", line 561
    this->visit_expr(*print_stmt->m_values[i]);
  File "../libasr/asr.h", line 5202
  File "../libasr/asr.h", line 4981
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/implied_do_loops.cpp", line 587
    current_expr = const_cast<ASR::expr_t**>(&(string_format_stmt->m_args[i]));
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/implied_do_loops.cpp", line 438
    replacer.replace_expr(*current_expr);
  File "../libasr/asr.h", line 46097
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/implied_do_loops.cpp", line 242
    ASRUtils::duplicate_type_with_empty_dims(al, x->m_type))));
  File "../libasr/asr_utils.h", line 2682
  File "../libasr/asr_utils.h", line 2525
  File "../libasr/asr_utils.h", line 2640
LCompilersException: Not implemented 8
```

**Closed** 2024-08-23 14:41 UTC
Labels: SNAP
