### ISSUE TITLE
Are arrays case-sensitive?

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#251] opened 2022-08-15 08:24 UTC
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/166

I have tried to run the following code:
```
integer, dimension(3) :: A
a = [ 1, 2, 3 ]
```
, and I have got an extraordinary error:
```
Variable 'a' not declared.
```

Probably, it is linked with https://gitlab.com/lfortran/lfortran/-/issues/145.

**Comment by everythingfunctional** [comment] 2022-11-30 22:47
I found another thing that appears to be case-sensitive, procedure names. I.e.:

```fortran
module hello_m
  implicit none
  private
  public :: say_hello
  
  interface say_hello
    module procedure Say_Hello_To
  end interface
contains
  subroutine say_hello_to(name)
    character(len=*), intent(in) :: name
    print *, "Hello, " // name // "!"
  end subroutine
end module

program test
  use hello_m
  implicit none
  call say_hello("World")
end program
```

gives:

```text
semantic error: Symbol 'Say_Hello_To' not declared
 --> input:1:2
  |
1 | module hello_m
  |  ^ 


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).
```

Note, it seems to be dependent on which one is capitalized as

```fortran
module hello_m
  implicit none
  private
  public :: say_hello
  
  interface say_hello
    module procedure say_hello_to
  end interface
contains
  subroutine Say_Hello_To(name)
    character(len=*), intent(in) :: name
    print *, "Hello, " // name // "!"
  end subroutine
end module

program test
  use hello_m
  implicit none
  call say_hello("World")
end program
```

gives

```text
6678368
ERROR: The code could not be compiled. Either there is a compile-time error or there is an issue at our end.
```

from dev.lfortran.org (which is awesome by the way).

**Comment by certik** [comment] 2022-12-01 06:48
Thanks. The appropriate place in AST to ASR is missing `to_lower`.

**Comment by HarshitaKalani** [comment] 2023-08-07 16:26
The following works with the latest main
```
integer, dimension(3) :: A
a = [ 1, 2, 3 ]
```

This still gives the error:
```
module hello_m
  implicit none
  private
  public :: say_hello
  
  interface say_hello
    module procedure Say_Hello_To
  end interface
contains
  subroutine say_hello_to(name)
    character(len=*), intent(in) :: name
    print *, "Hello, " // name // "!"
  end subroutine
end module

program test
  use hello_m
  implicit none
  call say_hello("World")
end program
```
```
semantic error: Symbol 'Say_Hello_To' not declared
 --> a.f90:1:2
  |
1 | module hello_m
  |  ^ 


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

This following works fine too
```
module hello_m
  implicit none
  private
  public :: say_hello
  
  interface say_hello
    module procedure say_hello_to
  end interface
contains
  subroutine Say_Hello_To(name)
    character(len=*), intent(in) :: name
    print *, "Hello, " // name // "!"
  end subroutine
end module

program test
  use hello_m
  implicit none
  call say_hello("World")
end program
```
```console
(lf) harshita@harshita-linux:~/Desktop/lfortran$ lfortran a.f90
Hello, World!
```

That, I guess, means we're lowering the `subroutine name` by `to_lower` but not doing this for `module procedure name`

**Comment by HarshitaKalani** [comment] 2023-08-18 08:08
```
module hello_m
    implicit none
    public :: say_hello
    
    interface say_hello
      module procedure Say_hello_to
    end interface
  contains
    subroutine Say_hello_to()
    end subroutine
  end module
  
  program test
    use hello_m
    implicit none
    call Say_hello_to()
  end program

```
```console
(lf) harshita@harshita-linux:~/Desktop/lfortran$ lfortran b.f90
semantic error: Symbol 'Say_hello_to' not declared
 --> b.f90:1:2
  |
1 | module hello_m
  |  ^ 


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
```
The issue is there even when procedure name and subroutine name are same (except when it is lowercase totally)

**Comment by HarshitaKalani** [comment] 2024-03-13 16:32
Closing this issue as it works with the latest main.

**Closed by HarshitaKalani** 2024-03-13 16:32 UTC
