### ISSUE TITLE
how to compile but not immediately run?

### ISSUE THREAD

**Issue by harperjf** [lfortran/lfortran#3794] opened 2024-04-06 05:05 UTC
Lfortran compiles and immediately runs a program if no compilation errors were found. Every other compiler makes an object file, called either a.out or whatever the -o option specified, and running the program happens only when one executes the object file. Is there an option to do that? ```man ifortran``` seemed not to provide one.

**Comment by certik** [comment] 2024-04-06 05:28
Duplicate of https://github.com/lfortran/lfortran/issues/3795.

**Closed by certik** 2024-04-06 05:28 UTC
