### ISSUE TITLE
subroutine can not change the argument

### ISSUE THREAD

**Issue by Euler-37** [lfortran/lfortran#1027] opened 2022-11-21 02:12 UTC
[https://dev.lfortran.org/](https://dev.lfortran.org/)
``` fortran
program main
    integer::x
    call test(1,x)
    write(*,*)x
end program main

subroutine test(i,a)
    integer,intent(in)::i
    integer::a
    a=i
end subroutine test
```
the output is
0

and the converted c++ code is

``` cpp
// Implementations
void test(int32_t i, int32_t &a)
{
    a = i;
}

namespace {

void main2() {
    int32_t x;
    test(1, x);
    std::cout << x << std::endl;
}
```

**Comment by certik** [comment] 2022-11-21 03:03
Thanks @Euler-37 for reporting it!

I think this is probably a bug in the WASM backend, since if you put this into a file and execute like this, it works:
```console
$ cat b.f90 
program main
    integer::x
    call test(1,x)
    write(*,*)x
end program main

subroutine test(i,a)
    integer,intent(in)::i
    integer::a
    a=i
end subroutine test
$ lfortran b.f90
1
```

**Comment by Euler-37** [comment] 2022-11-21 03:21
``` fortran
program main
    integer::x=10
    integer::y(1)=[20]
    write(*,*)x
    write(*,*)y(1)
    call test(1,x)
    write(*,*)x
    call test(2,y(1))
    write(*,*)y(1)
end program main

subroutine test(i,a)
    integer,intent(in)::i
    integer,intent(inout)::a
    a=i
end subroutine test
```
 And the result is still wrong  for Passing array.

And I tried on lfortran
``` sh
$ lfortran b.f90
10
20
1
20
$ lfortran --version
LFortran version: 0.18.0-67-g164a0837f
Platform: Linux
Default target: x86_64-pc-linux-gnu
```

**Comment by certik** [comment] 2022-11-21 14:11
Indeed, I can also reproduce it even with LLVM:
```console
/tmp $ gfortran a.f90 
/tmp $ ./a.out 
          10
          20
           1
           2
/tmp $ lfortran a.f90 
10
20
1
20
```

**Comment by Shaikh-Ubaid** [comment] 2022-11-21 15:11
For the following example:
```fortran
program main
    integer::x
    call test(1,x)
    write(*,*)x
end program main

subroutine test(i,a)
    integer,intent(in)::i
    integer::a
    a=i
end subroutine test
```
The C++ output I get is:
```cpp
// Implementations
void test(int32_t i, int32_t a)
{
    a = i;
}

namespace {

void main2() {
    int32_t x;
    test(1, x);
    std::cout << x << std::endl;
}
```

The second parameter of `test()` is not passed by reference.

I think, this is because, the `cpp` backend declares parameters by reference only when the variables have intent `inout` or `out`.
https://github.com/lfortran/lfortran/blob/6cb62b1e0e96c6e4c0ba6ddb201bfc4e5c1ab670/src/libasr/codegen/asr_to_cpp.cpp#L216-L218

**doubt:** In Fortran, is intent `unspecified` also passed by reference?

**Comment by Shaikh-Ubaid** [comment] 2023-08-27 00:23
The code shared in the description of this issue seems to work with `LLVM` and `WASM` backends. Is it safe to close this issue?

**Comment by certik** [comment] 2023-08-28 00:54
Both of the examples above now work both locally as well as at dev.lfortran.org. For example the second example:
```
$ lfortran a.f90 
10
20
1
2
$ gfortran a.f90&& ./a.out 
          10
          20
           1
           2
```

**Closed** 2023-08-28 00:55 UTC
