### ISSUE TITLE
Windows CI failing

### ISSUE THREAD

**Issue by czgdp1807** [lfortran/lfortran#3473] opened 2024-02-21 18:04 UTC
https://github.com/lfortran/lfortran/actions/runs/7993021427/job/21827898125 - Seems like CMake is unable to detect any package on Windows. Starts with ZLIB but if you turn it off then we see the error with ZSTD.

**Comment by certik** [comment] 2024-02-21 21:59
Duplicate of https://github.com/lfortran/lfortran/issues/3467.

**Closed by certik** 2024-02-21 21:59 UTC
