### ISSUE TITLE
[SciPy]: ```--show-asr``` halting on execution

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#709] opened 2022-09-08 10:11 UTC
File: ```scipy/linalg/src/id_dist/src/idd_frm.f```
Halts on executing to: ```/src/bin/lfortran --show-asr --implicit-typing --allow-implicit-interface --fixed-form /home/pranavchiku/scipy/scipy/linalg/src/id_dist/src/idd_frm.f```

**Comment by Smit-create** [comment] 2022-09-10 07:07
I think the issue is with the `--show-ast`. `--show-ast` halts for me which means ASR won't be generated until we have AST.

**Comment by Pranavchiku** [comment] 2022-09-12 09:56
Yeah!

**Comment by konradha** [comment] 2022-09-12 10:06
No, that's unfortunately not the issue. The fixed form parser currently does not tokenize `STOP` -- should get fixed with #695

**Comment by Pranavchiku** [comment] 2022-09-12 10:08
Ohh okay :)

**Comment by konradha** [comment] 2022-09-23 13:33
This is fixed. We should verify the ASR generated for `scipy/linalg/src/id_dist/src/idd_frm.f` though.

**Closed by konradha** 2022-09-23 13:33 UTC
