### ISSUE TITLE
undefined symbols for architecture arm64 when changing name of variable in interface

### ISSUE THREAD

**Issue by BlameTroi** [lfortran/lfortran#3285] opened 2024-02-02 15:56 UTC
While working with a sample from the web, I noticed a flycheck/linter complaint about variable masking.

```
integer, dimension(10) :: a
interface
subroutine fill_array(a)
integer, dimension(:) intent(out) :: a
end subroutine fill_array
end interface
```

Everything worked ok in both gfortran and lfortran, but when I changed the dummy variable to `aa` from `a` lfortran fails when linking. gfortran works OK.

Sample code and run attached.
[issue.txt](https://github.com/lfortran/lfortran/files/14142403/issue.txt)

**Comment by certik** [comment] 2024-02-02 20:57
Great catch, thanks! There are two bugs, once is #3288. The main bug in this issue is:
```fortran
subroutine fill_array(a)
integer, dimension(:), intent(out) :: a
integer :: i
do i = 1, 10
    a(i) = i
end do
end subroutine

program dummy_array_assumed
integer, dimension(10) :: a
interface
    subroutine fill_array(aa)
    integer, dimension(:), intent(out) :: aa
    end subroutine fill_array
end interface
call fill_array(a)
print *, a
end program
```
Which gives:
```console
$ lfortran a.f90
Undefined symbols for architecture arm64:
  "_fill_array_aa", referenced from:
      _main in a.out.tmp.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
The command 'clang -o a.out a.out.tmp.o  -L"/Users/ondrej/repos/lfortran/lfortran/src/bin/../runtime" -Wl,-rpath,"/Users/ondrej/repos/lfortran/lfortran/src/bin/../runtime" -llfortran_runtime -lm' failed.
```

The issue is in the generated LLVM code:
```console
$ lfortran a.f90 --show-llvm
[...]
define void @fill_array_a(i32* %a, i32* %__1a, i32* %__2a) {
...
}
...
declare void @fill_array_aa(i32*, i32*, i32*)
```
Where the name of the argument makes it into the name of the function, and since the argument is named differently, the function is not found.

The name of arguments are irrelevant to the (binary) interface, so it's a bug.

This is caused by the `pass_array_by_data` ASR pass. In the above case one can skip it:
```console
$ lfortran a.f90 --skip-pass=pass_array_by_data
1 2 3 4 5 6 7 8 9 10 
```
But the pass is needed in other cases I think, so we need to fix it.

CC @czgdp1807.

**Comment by czgdp1807** [comment] 2024-02-02 21:10
I see. The underlying issue is how we generate names of two functions. Seems like they shouldn't rely on the name of arguments. May be the index of argument and the type of argument.

**Comment by czgdp1807** [comment] 2024-02-04 08:17
Will be fixed on Wednesday.

**Closed** 2024-02-07 10:43 UTC
Labels: bug

**Comment by certik** [comment] 2024-02-08 22:04
I can confirm that the example from https://github.com/lfortran/lfortran/issues/3285#issuecomment-1924686609 now works:
```console
$ lfortran a.f90 
1 2 3 4 5 6 7 8 9 10 
$ gfortran a.f90 && ./a.out 
           1           2           3           4           5           6           7           8           9          10
```
