### ISSUE TITLE
Duplicate deallocate in the ASR

### ISSUE THREAD

**Issue by Thirumalai-Shaktivel** [lfortran/lfortran#2763] opened 2023-10-31 02:42 UTC
```fortran
program main
integer, allocatable :: d(:)
allocate(d(3))
end program
```
ASR after passes:
```clojure
...
(ImplicitDeallocate
    [(Var 2 d)]
)
(ImplicitDeallocate
    [(Var 2 d)]
)
...
```

The ImplicitDeallocate nodes are inserted in `array_op` and `insert_deallocate` passes. I think we have to remove this in `array_op`.

**Comment by Thirumalai-Shaktivel** [comment] 2023-10-31 02:44
Also, we have to make sure there is no `ExplicitDeallocate`
```fortran
program main
integer, allocatable :: d(:)
allocate(d(3))
deallocate(d)
end program
```
ASR after passes
```clojure
(ExplicitDeallocate
    [(Var 2 d)]
)
(ImplicitDeallocate
    [(Var 2 d)]
)
(ImplicitDeallocate
    [(Var 2 d)]
)]
```

**Comment by kmr-srbh** [comment] 2024-05-26 09:05
@Thirumalai-Shaktivel as we are calling `deallocate` on `d` explicitly here, it will add the `ExplicitDeallocate` node, right? In this case, we have to remove the `ImplicitDeallocate` node as it is redundant. In case the user does not deallocate a variable explicitly, then we can have the `ImplicitDeallocate` to free the memory for us.

I am working on a fix for this and hence need to get this clarified. Could you please guide me on this?

**Comment by kmr-srbh** [comment] 2024-05-26 09:11
Also, as you have rightly pointed out, we have a fair degree of redundancy related to the addition of the `ImplicitDeallocate` node. The AST body visitor automatically adds an `ImplicitDeallocate` node when it sees an `allocatable`. The same is true for the addition of `ExplicitDeallocate` node for a `deallocate` call. The first addition occurs here. The duplication is caused by the passes which you rightly stated above.

Could you please guide me on why the `insert_deallocate` pass is required? Isn't it redundant?

**Closed** 2024-11-16 05:35 UTC
